### ISSUE TITLE
MX250 don't need to install OpenCL SDK as being integrated presumably in the driver

### ISSUE THREAD

**Issue by D2Joy** [whiteblackitty/SQLCipher-Password-Cracker-OpenCL#1]
I installed CUDA in the first place, and it works. Then I read another tutorial where they use oclDeviceQuery to check for openCl info, by which I found Opencl 1.2 and CUDA 10.1 are right there even after I uninstalled CUDA 10.0. The python script still runs without problem.

**Comment by whiteblackitty** [comment]
Hi, D2Joy. Thanks for your information. Yes, you discovered a relatively confusing situation. In fact, the OpenCL code can run without any OpenCL SDK because running them only needs OpenCL runtime, which has been always integrated in normal graphics driver for these recently-released GPUs like MX250. However, you need OpenCL SDK to build the pyOpenCL for your GPU platform. Once the build complete, you don't need OpenCL SDK anymore.

**Comment by D2Joy** [comment]
Oh, Right. The OpenCL method is undoubtedly superior than CPU one. Am I right to see it as the first option for general password bruteforce and do you mind my citing it elsewhere?

**Comment by whiteblackitty** [comment]
Of course you can cite this repo. The OpenCL is indeed an important tool for GPU programming, but the CUDA language is also important. This repo cannot brute force other kind of encryption. Up to now, it can only deal with AES-256-CBC encryption with PBKDF2 and no HMAC.  To get a large variety of password bruteforcing code in OpenCL, you can go to the Hashcat website.
